nom = input("Entrez votre nom : ")
prenom = input("Entrez votre prénom : ")
age = input("Entrez votre âge : ")
sexe = input("Entrez votre sexe : ")
email = input("Entrez votre adresse email : ")
print("\n--- Vos informations personnelles ---")
print("Nom :", nom)
print("Prénom :", prenom)
print("Âge :", age)
print("Sexe :", sexe)
print("Email :", email)
